title: Dustin Marshall
logo: "/images/logo.png"
description: >
  I have a MSc in <a href="https://capp.uchicago.edu/">Computational Analysis and Public Policy</a> 
  (MSCAPP) from the University of Chicago, where I excelled in advanced coursework in software 
  engineering, cloud computing, database development, machine learning, and econometrics.
  <br><br>
  I've worked as a Summer Associate at the Rockefeller Foundation's Data Science team, a graduate student 
  researcher in applied data science at the <a href="https://bfi.uchicago.edu/development-innovation-lab/">
  Development Innovation Lab</a> (DIL) under Nobel laureate <a href="https://economics.uchicago.edu/directory/michael-kremer">
  Michael Kremer</a>, and prior to graduate school, I worked at the Center for Effective Global Action (CEGA) supporting applied 
  economics and data science research in low- and middle-income countries.
  <br><br>
  <a href="https://www.linkedin.com/in/dustin-marshall-b1151184/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-35FELT9N8M 